source 'https://rubygems.org'

gem 'berkshelf', '> 3.1'
gem 'chef'
gem 'chefspec'
gem 'foodcritic'
gem 'foodcritic-rackspace-rules'
gem 'guard'
gem 'guard-foodcritic'
gem 'guard-rubocop'
gem 'ipaddress'
gem 'kitchen-vagrant'
gem 'ohai'
gem 'rake'
gem 'rubocop'
gem 'test-kitchen'
gem 'vagrant-wrapper'
